site_name: AEGIS - Documentation projet

theme:
  name: "material"
  palette:  # Light and dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  font:
    text: Oxygen
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow

plugins:
  - mkdocstrings
  - search
  - termynal

extra_css:
  - style.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

nav:
  - Accueil: index.md
  - Zigbee:
      - Installation: 01-zigbee-setup.md
      - Capteurs Aqara: 02-capteurs-aqara.md
  - Application web:
      - Design + strategie: 07-design-interface.md
      - Stack technique: 08-stack-technique.md
      - Guide integration UI: 09-guide-integration-ui.md
  - Alarme:
      - Alarme, camera & orchestrateur: 04-alarme-camera.md
      - Architecture MQTT: 05-architecture-mqtt.md
      - Messagerie (notifier): 14-messagerie.md
